### ISSUE TITLE
Updates required for release v1.6

### ISSUE THREAD

**Issue by raoanirudh** [GEMScienceTools/oq-engine-docs#16]
The following changes since v1.5 need to be documented in the OpenQuake-engine manual:

* describe the NRML v0.5 schemas for fragility and vulnerability
* fragility models can be specified for loss types other than structural
* describe the new consequence model schema
* describe the scenario damage extension to compute consequences
* describe the new pmf vulnerability option
* describe how to run scenarios with multiple gsims
* describe the priority order for hazard sites
* describe the unified job option for scenarios and event based
* replace `--load-gmf` with `gmfs_file`, and `gmfs_csv`
* include the correct path to the updated demos in risklib
* make the description of the demos consistent with the updated demos

**Comment by raoanirudh** [comment]
@micheles, @daniviga: please add to this list if anything is missing.

**Comment by micheles** [comment]
You can also document the fact that now one must set the `lossCategory` to be consistent with the name of the key in the `job.ini` file.

**Comment by daniviga** [comment]
About the WebUI I would keep it only in the wiki/doc for this release and maybe move it in the manual for 1.7.

**Comment by micheles** [comment]
Should we close this issue now?

**Comment by raoanirudh** [comment]
The only two items pending from the list are:
* describe how to run scenarios with multiple gsims
* describe the priority order for hazard sites

I think we should close this issue and add the above items to the to-do list for the next version of the manual
